<?php

namespace mdw\gestionBundle\Repository;

/**
 * Formation_personneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Formation_personneRepository extends \Doctrine\ORM\EntityRepository
{
}
